services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://thingdata:thingdata@db:5432/thingdata
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    working_dir: /app

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=thingdata
      - POSTGRES_PASSWORD=thingdata
      - POSTGRES_DB=thingdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thingdata"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
