services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://thingdata:thingdata@db:5432/thingdata
      - ENVIRONMENT=production  # Changed from development
      - LOG_LEVEL=INFO         # Changed from DEBUG
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs       # Added logs persistence
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=thingdata
      - POSTGRES_PASSWORD=thingdata
      - POSTGRES_DB=thingdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Added initialization scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thingdata"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: thingdata_postgres_data  # Named volume for easier management