services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://thingdata:thingdata@db/thingdata_test
      - ENVIRONMENT=test
      - LOG_LEVEL=DEBUG
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/src/app
      - ./tests:/src/tests
    command: pytest -v

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=thingdata
      - POSTGRES_PASSWORD=thingdata
      - POSTGRES_DB=thingdata_test
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thingdata"]
      interval: 5s
      timeout: 5s
      retries: 5
