services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "5678:5678"  # For debugger
    environment:
      - CONFIG_FILE=/src/config/development.yaml
      - DATABASE_URL=postgresql://thingdata:thingdata@db/thingdata
      - ENVIRONMENT=development
      - PYTHONPATH=/src
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./data:/data
      - ./logs:/logs
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=thingdata
      - POSTGRES_PASSWORD=thingdata
      - POSTGRES_DB=thingdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thingdata"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
