# Development configuration
server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1
  debug: true

database:
  url: "postgresql://thingdata:thingdata@db/thingdata"
  echo_sql: true
  pool_size: 20
  max_overflow: 10

storage:
  s3_endpoint: "http://minio:9000"
  bucket: "thingdata"
  local_cache: "/data/local_cache"
  cache_ttl: 604800  # 7 days in seconds

federation:
  discovery_interval: 300  # 5 minutes
  sync_interval: 600      # 10 minutes
  retry_delays: [5, 15, 30, 60, 120]
  trust_threshold: 0.7

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - [%(correlation_id)s] %(message)s"
  max_size: 10485760  # 10MB
  backup_count: 5
  log_sql: true

monitoring:
  enabled: true
  interval: 60
  metrics:
    - system_resources
    - request_timing
    - database_connections
    - cache_stats
    - federation_status

development:
  mock_federation: true
  generate_test_data: true
  profile_endpoints: true
  debug_toolbar: true
  cors_origins: ["http://localhost:3000"]
